---
- name: Install set-interface-names bash script
  become: yes
  become_user: root
  copy:
    src: set-interface-names
    dest: /usr/sbin
    mode: 0755
    owner: root

- name: Install set-interface-names service
  become: yes
  become_user: root
  copy:
    src: set-interface-names.service
    dest: /lib/systemd/system/
    mode: 0644
    owner: root

- name: Enable set-interface-names with symlink
  become: yes
  become_user: root
  file: src=/lib/systemd/system/set-interface-names.service dest=/lib/systemd/system/sysinit.target.wants/set-interface-names.service owner=root group=root mode="0644" state=link
