---
- hosts: localhost
  remote_user: pexip
  become: yes
  become_user: pexip
  roles:
    - role: apt
    - role: fail2ban
    - role: nginx
    - role: set-interface-names
    - role: installwizard
    - role: security
    - role: version
