---
- hosts: localhost
  remote_user: pexip
  become: yes
  become_user: pexip
  roles:
    - role: apt
    - role: fail2ban
    - role: nginx
    - role: munin
    - role: set-interface-names
    - role: installwizard
    - role: security

# TODO: see if below is required?
#       - { src: /tmp/_rpbuild/motd', dest: '/etc/' }
#    - name: "Change GRUB_CMD_LINE_LINUX_DEFAULT to enable serial adapters"
#      become: yes
#      become_user: root
#      lineinfile:
#        dest: /etc/default/grub
#        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
#        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash security=selinux selinux=1 console=ttyS0 console=tty0 earlyprintk=ttyS0 rootdelay=300 fsck.mode=force fsck.repair=yes"'
#        backrefs: yes
#      register: grubcmdline
#    - name: "update-grub"
#      become: yes
#      become_user: root
#      command: update-grub
#      when: grubcmdline.changed
