---
- name: Calculate numericversion
  command: /opt/rp-turn/bin/python3 -c "import rp_turn; print(rp_turn.__version__)"
  register: numericversion_command

- name: Calculate pseudoversion
  become: yes
  become_user: root
  command: git rev-list HEAD --count
  register: pseudoversion_command

- name: Set version facts
  ansible.builtin.set_fact:
    build_numericversion: "{{ numericversion_command.stdout }}"
    build_pseudoversion: "{{ pseudoversion_command.stdout }}"
    build_date: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- name: Write out /etc/rp-turn-release
  become: yes
  become_user: root
  ansible.builtin.template:
    src: rp-turn-release
    dest: /etc/rp-turn-release
    owner: root
    group: root
    mode: '0644'

- name: Set RP Turn MOTD
  become: yes
  become_user: root
  copy:
    src: 99-rp-turn-motd
    dest: /etc/update-motd.d/
    mode: 0755
    owner: root

- name: Copy RP Turn license
  copy:
    src: LICENSE
    dest: /home/pexip/LICENSE
    mode: 644
    owner: pexip
