---
- name: Install rp_turn python application
  become: yes
  become_user: root
  ansible.builtin.pip:
    name: /run/rp-turn
  when: ansible_distribution_release != 'bookworm'

- name: Install rp_turn python application
  become: yes
  become_user: root
  ansible.builtin.pip:
    name: /run/rp-turn
    extra_args: --break-system-packages
  when: ansible_distribution_release == 'bookworm'

- name: Install installwizard bash script
  become: yes
  become_user: root
  copy:
    src: installwizard
    dest: /usr/bin/installwizard
    mode: 0755
    owner: root

- name: Install profile file to invoke installwizard on first login
  copy:
    src: .profile
    dest: /home/pexip/
    mode: 0644
