---
- name: Install munin configuration
  become: yes
  become_user: root
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
  with_list:
    - { src: munin.conf, dest: /etc/munin/munin.conf }
    - { src: munin-node.conf, dest: /etc/munin/munin-node.conf }

- name: Disable most default munin plugins
  become: yes
  become_user: root
  file:
    path: "/etc/munin/plugins/{{ item }}"
    state: absent
  with_list:
#    - cpu
    - df
    - df_inode
    - diskstats
    - entropy
    - forks
    - fw_packets
    - if_err_eth0
#    - if_eth0
    - interrupts
    - irqstats
#    - load
#    - memory
    - munin_stats
    - netstat
    - open_files
    - open_inodes
    - processes
    - proc_pri
    - swap
    - threads
    - uptime
    - users
    - vmstat

- name: Create munin stats symlink
  become: yes
  become_user: root
  file:
    src: /var/cache/munin/www/localdomain/localhost.localdomain
    dest: /var/www/stats/img/localhost.localdomain
    owner: root
    group: root
    mode: 0644
    state: link
    force: yes
