name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  ansible:
    uses: ./.github/workflows/ansible.yml
  cloud-init:
    uses: ./.github/workflows/cloud-init.yml
  python:
    uses: ./.github/workflows/python.yml
