name: Python

on:
  workflow_call:

jobs:
  black:
    strategy:
      matrix:
        py-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run invoke python.black --check

  isort:
    strategy:
      matrix:
        py-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run invoke python.isort --check

  mypy:
    strategy:
      matrix:
        py-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run invoke python.mypy

  pylint:
    strategy:
      matrix:
        py-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run invoke python.pylint

  pytest:
    strategy:
      matrix:
        py-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run invoke python.pytest
